# Generated by Django 4.2 on 2024-01-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
    ]
