# Generated by Django 4.2 on 2024-01-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order_admin_order_oid_order_price_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('avatar', models.CharField(max_length=256, verbose_name='头像')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态'),
        ),
    ]
